version: 2.1

executors:
  bash:
    working_directory: ~/engineering
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin:/root/.local/bin
    docker:
      - image: cimg/base:stable

commands:
  shellcheck:
    steps:
      - run: wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-v0.6.0.linux.x86_64.tar.xz" | tar -xJv; cp shellcheck-v0.6.0/shellcheck /usr/bin
      - run: find deploy/ src/ dev-resources/ -type f | grep -v qemu-arm-static | grep -vE '(\.(py|pyc|sql|ya?ml|md|csv|json|jsonl|jpg|txt)$|vimrc|Dockerfile|.DS_Store)' | xargs shellcheck --shell bash --severity error
  install_aws_cli:
    steps:
      - run: apt update; apt install -y -qq bc python3-pip; pip3 install awscli --upgrade --user

jobs:
  test-and-publish:
    executor: bash
    steps:
      - checkout
      - shellcheck
      - install_aws_cli
      - run: deploy/bin/publish-image

workflows:
  commit:
    jobs:
      - test-and-publish
