#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" && cd "${dir}/.."
app="$(basename $(dirname $dir))"

publish(){
  local tag="$1"
  local tag_suffix=''

  cat "${dir}/../deploy/default/${tag}.Dockerfile" >Dockerfile

  tag_suffix='dev'
  tag="${tag}_${tag_suffix}"

  docker build --rm -t "${app}:${tag}" .
  docker tag "${app}:${tag}" "$app"

  if [[ -f Dockerfile ]]; then rm Dockerfile; fi
}

publish 'bash-arm' \
  && publish 'java-arm' \
  && publish 'bash'     \
  && publish 'java'     \
  && publish 'debian'
