#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )" && cd "$dir"
app="$(basename $dir)"

publish(){
  local tag="$1"
  local tag_suffix='dev'

  cat "${dir}/deploy/default/${tag}.Dockerfile" >Dockerfile

  tag="${tag}-${tag_suffix}"

  docker build --rm -t "${app}:${tag}" .
  docker tag "${app}:${tag}" "$app"

  if [[ -f Dockerfile ]]; then rm Dockerfile; fi
}

publish 'bash-arm' \
  && publish 'java-arm' \
  && publish 'bash'     \
  && publish 'java'     \
  && publish 'debian'
